### ISSUE TITLE
Customise the 'data' array

### ISSUE THREAD

**Issue by mar627** [makkinga/statamic-hooker#2]
Hey!

This has helped set up notifications for new users on my site, thanks!

`'data'     => reset($event)->data->toArray()`

Is there any easy fixes in that line that can prevent the data array from containing email addresses and hashed passwords? I send the webhook on a user save event to a third party service and then it goes to a few places.. I'd just rather not include that stuff for extra peace of mind.

A solution in the UI would be wicked, but I'll take a quick edit if you've got one :)

**Comment by makkinga** [comment]
Hi @mar627 ,

Sorry for the late response, and thanks for your interest in the addon.
I'll try to have a look into this in the coming week. 
Of course if you have already fixed this issue while you were waiting for my answer the past 29 days feel free to share! :p

Gydo

**Comment by makkinga** [comment]
Thanks again @mar627 for this feature request!
I have added it to the addon, hope this suits your needs

**Comment by makkinga** [comment]
Each webhook now has a `Hidden keys` list. All keys entered here will be removed from the requests

![image](https://user-images.githubusercontent.com/3294611/57918190-87c87680-7896-11e9-9b0a-e78de6af3111.png)

**Comment by mar627** [comment]
> Each webhook now has a `Hidden keys` list. All keys entered here will be removed from the requests
> 
> ![image](https://user-images.githubusercontent.com/3294611/57918190-87c87680-7896-11e9-9b0a-e78de6af3111.png)

Where is this?

Hey Makkinga, finally have a chance to test the hidden keys, but I can't find it in the ui? I've removed and reinstalled, update:addons, but its nowhere!

Thanks
